name: Run test suite and build wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: gijzelaerr/monetdb:latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: run test action
      run: .inside/test.sh ${{ matrix.python-version }}

  wheel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: make wheels
      run: .inside/make_wheel.sh ${{ matrix.python-version }} 

  quality:
    steps:
      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.1.0

