name: Run test suite and build wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_linux:
    runs-on: ubuntu-18.04
    container: gijzelaerr/monetdb:test38
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: run tests on Linux
        run: scripts/test.sh

  wheel_linux:
    runs-on: ubuntu-18.04
    container: gijzelaerr/monetdb:wheel
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: make linux binary wheels
        run: scripts/make_wheel.sh ${{ matrix.python-version }}

  quality_linux:
    runs-on: ubuntu-18.04
    container: gijzelaerr/monetdb:test38
    steps:
      - uses: actions/checkout@v2
      - name: Run mypy static code checks
        run: scripts/mypy.sh

  pycodestyle_linux:
    runs-on: ubuntu-18.04
    container: gijzelaerr/monetdb:test38
    steps:
      - uses: actions/checkout@v2
      - name: Check the python coding style
        run: scripts/pycodestyle.sh

  windows_wheel:
    runs-on: windows-2019
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Windows binary wheel
        run: scripts/win_wheel.ps1

  osx_wheel:
    runs-on: macos-10.15
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: OS X binary wheel
        run: scripts/osx_wheel.sh
