name: Run test suite and build wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-18.04
    container: gijzelaerr/monetdb:latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: run test action
      run: .inside/test.sh ${{ matrix.python-version }}

  wheel:
    runs-on: ubuntu-18.04
    container: gijzelaerr/monetdb:latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: make wheels
      run: .inside/make_wheel.sh ${{ matrix.python-version }} 

  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.1.0

  windows:
    runs-on: windows-2019
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2    
      - name: build
        run: python3 setup.py build

  osx:
    runs-on: macos-10.15
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2    
      - name: build
        run: python3 setup.py build


